peridot: sepolicy: cleanup and drop neverallow policies
* This reverts commit ace561c
* This reverts commit 2519390
* This reverts commit cafe269

FAILED: out/soong/.intermediates/system/sepolicy/sepolicy_neverallows/android_common/policy
out/host/linux-x86/bin/checkpolicy -M -c 30 -o out/soong/.intermediates/system/sepolicy/sepolicy_neverallows/android_common/policy out/soong/.intermediates/system/sepolicy/sepolicy_neverallows.checkpolicy.conf/android_common/sepolicy_neverallows.checkpolicy.conf # hash of input list: 3dd72144341d878094bd899c418dfc99c9016b3792c41283bd1afc203eecd905
libsepol.report_failure: neverallow on line 295 of system/sepolicy/private/property.te (or line 65917 of out/soong/.intermediates/system/sepolicy/sepolicy_neverallows.checkpolicy.conf/android_common/sepolicy_neverallows.checkpolicy.conf) violated by allow hal_graphics_composer_default system_prop:file { read open };
libsepol.report_failure: neverallow on line 2094 of system/sepolicy/private/domain.te (or line 33439 of out/soong/.intermediates/system/sepolicy/sepolicy_neverallows.checkpolicy.conf/android_common/sepolicy_neverallows.checkpolicy.conf) violated by allow system_server vendor_file:file { read getattr open };
libsepol.report_failure: neverallow on line 2094 of system/sepolicy/private/domain.te (or line 33439 of out/soong/.intermediates/system/sepolicy/sepolicy_neverallows.checkpolicy.conf/android_common/sepolicy_neverallows.checkpolicy.conf) violated by allow surfaceflinger vendor_file:file { read getattr open };
libsepol.report_failure: neverallow on line 2055 of system/sepolicy/private/domain.te (or line 33252 of out/soong/.intermediates/system/sepolicy/sepolicy_neverallows.checkpolicy.conf/android_common/sepolicy_neverallows.checkpolicy.conf) violated by allow system_server vendor_file:file { open };
libsepol.report_failure: neverallow on line 2055 of system/sepolicy/private/domain.te (or line 33252 of out/soong/.intermediates/system/sepolicy/sepolicy_neverallows.checkpolicy.conf/android_common/sepolicy_neverallows.checkpolicy.conf) violated by allow surfaceflinger vendor_file:file { open };
libsepol.check_assertions: 5 neverallow failures occurred
Error while expanding policy

FAILED: //system/sepolicy:precompiled_sepolicy Compiling cil files for precompiled_sepolicy
Outputs: out/soong/.intermediates/system/sepolicy/precompiled_sepolicy/android_common/peridot/precompiled_sepolicy
Error: exited with code: 1
Command: out/host/linux-x86/bin/secilc -v -m -M true -G -c 30 out/soong/.intermediates/system/sepolicy/compat/plat_sepolicy_genfs_202504.cil/androidarm64>Output:
neverallow check failed at out/soong/.intermediates/system/sepolicy/plat_sepolicy.cil/android_common/plat_sepolicy.cil:26912 from system/sepolicy/private/s>  (neverallow domain base_typeattr_934 (service_manager (add find)))
    <root>
    allow at out/soong/.intermediates/system/sepolicy/vendor_sepolicy.cil/android_common/peridot/vendor_sepolicy.cil:11464
      (allow parts_app_202504 vendor_hal_displayfeature_xiaomi_default_202504 (service_manager (find)))
neverallow check failed at out/soong/.intermediates/system/sepolicy/plat_sepolicy.cil/android_common/plat_sepolicy.cil:14819 from system/sepolicy/private/d>  (neverallow base_typeattr_396 base_typeattr_397 (service_manager (find)))
    <root>
    allow at out/soong/.intermediates/system/sepolicy/vendor_sepolicy.cil/android_common/peridot/vendor_sepolicy.cil:11463
      (allow parts_app_202504 vendor_hal_displayfeature_xiaomi_service_202504 (service_manager (find)))
Failed to generate binary
Failed to build policydb

Signed-off-by: Shikhar <Krtonia@gmail.com>